//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucTap2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBA12Entities : DbContext
    {
        public DBA12Entities()
            : base("name=DBA12Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DB2401> DB2401 { get; set; }
        public virtual DbSet<DB2402> DB2402 { get; set; }
        public virtual DbSet<DB2403> DB2403 { get; set; }
        public virtual DbSet<DB2404> DB2404 { get; set; }
        public virtual DbSet<DB2405> DB2405 { get; set; }
        public virtual DbSet<DB2406> DB2406 { get; set; }
        public virtual DbSet<DB2407> DB2407 { get; set; }
        public virtual DbSet<DB2408> DB2408 { get; set; }
        public virtual DbSet<DB2409> DB2409 { get; set; }
        public virtual DbSet<DB2410> DB2410 { get; set; }
        public virtual DbSet<DB2411> DB2411 { get; set; }
        public virtual DbSet<DB2412> DB2412 { get; set; }
        public virtual DbSet<PC2401> PC2401 { get; set; }
        public virtual DbSet<PC2402> PC2402 { get; set; }
        public virtual DbSet<PC2403> PC2403 { get; set; }
        public virtual DbSet<PC2404> PC2404 { get; set; }
        public virtual DbSet<PC2405> PC2405 { get; set; }
        public virtual DbSet<PC2406> PC2406 { get; set; }
        public virtual DbSet<PC2407> PC2407 { get; set; }
        public virtual DbSet<PC2408> PC2408 { get; set; }
        public virtual DbSet<PC2409> PC2409 { get; set; }
        public virtual DbSet<PC2410> PC2410 { get; set; }
        public virtual DbSet<PC2411> PC2411 { get; set; }
        public virtual DbSet<PC2412> PC2412 { get; set; }
        public virtual DbSet<ST2401> ST2401 { get; set; }
        public virtual DbSet<ST2402> ST2402 { get; set; }
        public virtual DbSet<ST2403> ST2403 { get; set; }
        public virtual DbSet<ST2404> ST2404 { get; set; }
        public virtual DbSet<ST2405> ST2405 { get; set; }
        public virtual DbSet<ST2406> ST2406 { get; set; }
        public virtual DbSet<ST2407> ST2407 { get; set; }
        public virtual DbSet<ST2408> ST2408 { get; set; }
        public virtual DbSet<ST2409> ST2409 { get; set; }
        public virtual DbSet<ST2410> ST2410 { get; set; }
        public virtual DbSet<ST2411> ST2411 { get; set; }
        public virtual DbSet<ST2412> ST2412 { get; set; }
    }
}
