//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucTap2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB2401
    {
        public string MaCoQuan { get; set; }
        public string TenCoQuan { get; set; }
        public string NguoiNopThue { get; set; }
        public string MaSoThue { get; set; }
        public string TenNguoiNopThue { get; set; }
        public string MaNganhKDC { get; set; }
        public string TenNganhNgheKDC { get; set; }
        public string SoNhaDuongPho { get; set; }
        public string MaPhuongXa { get; set; }
        public string TenPhuongXa { get; set; }
        public string MaQuanHuyen { get; set; }
        public string TenQuanHuyen { get; set; }
        public string MaTinhThanhPho { get; set; }
        public string TenTinhThanhPho { get; set; }
        public string MaQuocGia { get; set; }
        public string TenQuocGia { get; set; }
        public Nullable<decimal> TongSoLaoDong { get; set; }
        public string NganhNgheKinhDoanh { get; set; }
        public string TenGiamDoc { get; set; }
        public string DTGiamDoc { get; set; }
        public string TenKeToanTruong { get; set; }
        public string DTKeToanTruong { get; set; }
        public string SoGiayTo { get; set; }
        public string NgayCap { get; set; }
        public string LoaiGiayTo { get; set; }
        public string SoGiayThongHanh { get; set; }
        public string SoTheQuanNhan { get; set; }
        public string SoCMNDCuaNguoiDaiDien { get; set; }
        public string SoGiayToKhac { get; set; }
        public string PhuongPhapTinhThue { get; set; }
        public string SoCMNDCuaChuDoanhNghiep { get; set; }
        public string SoGiayChungNhanDKKD { get; set; }
        public string NgayCapGiayChungNhanDKKD { get; set; }
        public string SoQuyetDinhThanhLap { get; set; }
        public string NgayQuyetDinhThanhLap { get; set; }
        public string SoHopDong { get; set; }
        public string NgayCapHopDong { get; set; }
        public string CoChiNhanh { get; set; }
        public string SoCMND { get; set; }
        public string SoHoChieu { get; set; }
        public string Chuong { get; set; }
        public string Khoan { get; set; }
        public string LoaiNguoiNopThue { get; set; }
        public string TrangThaiDKTCaNhan { get; set; }
        public string TrangThaiDKTToChuc { get; set; }
        public string NgayNhanToKhai { get; set; }
        public string LoaiHinhKinhTe { get; set; }
        public string TamNghiTuNgay { get; set; }
        public string TamNghiDenNgay { get; set; }
        public string LyDoTamNghi { get; set; }
        public string LyDoDongMSTCaNhan { get; set; }
        public string NgayDongTTCaNhan { get; set; }
        public string LyDoDongMSTTCToChuc { get; set; }
        public string NgayDongTTToChuc { get; set; }
        public string NoiSinh { get; set; }
        public string QuocTich { get; set; }
        public string NgaySinh { get; set; }
        public string SoHoChieuCuaCDN { get; set; }
        public string SoTheQuanNhanCuaCDN { get; set; }
        public string SoGiayThongHanhCuaCDN { get; set; }
        public Nullable<decimal> VonKinhDoanh { get; set; }
        public Nullable<decimal> NguonVonNSNN { get; set; }
        public Nullable<decimal> NguonVonNuocNgoai { get; set; }
        public Nullable<decimal> NguonVonKhac { get; set; }
        public string NgayBatDauKD { get; set; }
        public string DienThoaiBan { get; set; }
        public string SoMayLe { get; set; }
        public string DienThoaiDiDong { get; set; }
        public string DiaChiEmail { get; set; }
        public string SoTaiKhoan { get; set; }
        public string TenNganHang { get; set; }
        public string TenNganHang1 { get; set; }
        public string HThucHToan { get; set; }
        public string NamTaiChinhTu { get; set; }
        public string NamTaiChinhDen { get; set; }
        public string EmailThongBao { get; set; }
    }
}
