//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucTap2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC2403
    {
        public string MaSoThue { get; set; }
        public string TenNguoiNopThue { get; set; }
        public string MaPhong { get; set; }
        public string TenPhong { get; set; }
        public string MaCBQL { get; set; }
        public string TenCBQL { get; set; }
        public string ThoiGianTD { get; set; }
        public string CQTQuanLy { get; set; }
        public string MaPhongMoi { get; set; }
        public string TenPhongMoi { get; set; }
        public string MaCBQLMoi { get; set; }
        public string TenCBQLMoi { get; set; }
        public string CQTThucHien { get; set; }
        public string NNT { get; set; }
        public string NguoiTao { get; set; }
        public string NgayTao { get; set; }
        public string ThoiGianTao { get; set; }
        public string NguoiDoi { get; set; }
        public string NgayTD { get; set; }
    }
}
