//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucTap2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST2410
    {
        public string Kythue { get; set; }
        public string Madtnt { get; set; }
        public string Tendtnt { get; set; }
        public string Chuong { get; set; }
        public string Tmuc { get; set; }
        public Nullable<decimal> DkNop { get; set; }
        public Nullable<decimal> DkTam { get; set; }
        public Nullable<decimal> DkHoan { get; set; }
        public Nullable<decimal> PsNop { get; set; }
        public Nullable<decimal> PsTruyThu { get; set; }
        public Nullable<decimal> PsGiam { get; set; }
        public Nullable<decimal> PsXoaNo { get; set; }
        public Nullable<decimal> PsDaNop { get; set; }
        public Nullable<decimal> PsHoanNT { get; set; }
        public Nullable<decimal> PsHoanKT { get; set; }
        public Nullable<decimal> PsDaHoan { get; set; }
        public Nullable<decimal> CkNop { get; set; }
        public Nullable<decimal> CkTam { get; set; }
        public Nullable<decimal> CkHoan { get; set; }
    }
}
